name: Release
on:
  push:
    tags: release-v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/release-v}" >> "$GITHUB_ENV"

      - name: Build
        run: |
          mkdir dist
          zip -r dist/xkcd-new-tab_$RELEASE_VERSION.zip xkcd-new-tab/*

      - name: Upload & publish
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CWS_CLIENT_ID }}
          client-secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CWS_REFRESH_TOKEN }}
          file-path: dist/xkcd-new-tab_${{ env.RELEASE_VERSION }}.zip
          publish: true
